### ISSUE TITLE
Autodetect does not select DCS.openbeta folder

### ISSUE THREAD

**Issue by MacGynan** [Azza276/OGN_DCS_MOD_Sync#20]
When using the Auto detect in the options menu, it does not work with the DCS.openbeta folder or wherever it says (since i don't have that. Found that out when installing for Hunter).

On a side note: the custom directory in the options work perfectly.

**Comment by fiddyschmitt** [comment]
Thanks Mac, what is the full path to your DCS.openbeta folder?

**Comment by fiddyschmitt** [comment]
So far the autodetected folders are:

C:\Users\[Username]\Saved Games\DCS
C:\Users\[Username]\Saved Games\DCS.openbeta
C:\Users\[Username]\Saved Games\DCS World
C:\Users\[Username]\Saved Games\DCS.openalpha

**Comment by Azza276** [comment]
So, I have spoken to Hunter and I believe I know where the issue lies. 

I can confirm that Hunter has the .../DCS.openbeta folder in their Saved Games and there are no duplicates or other spellings.

In the OGN_DCS_Mod_Sync.cs (https://github.com/Azza276/OGN_DCS_MOD_Sync/blob/master/OGN_DCS_Mod_Sync/OGN_DCS_Mod_Sync_App/OGN_DCS_Mod_Sync.cs) file between lines 52 and 66 contains;

            //Determine the OGN Mods folder
            if (settings.AutodetectOgnModsFolder)
            {
                ognModFolder = FolderHelper.DetectOGNModsFolder();

                if (ognModFolder == null)
                {
                    SetCurrentAction("Could not autodetect OGN Mods folder. Please provide it using the Options window.");
                    return;
                }
            }
            else
            {
                ognModFolder = settings.OgnModsFolderOverride;
            }

This part of the code looks for the OGN Mods Folder. In Hunters case, as he was a new user of the App, he did not have that folder in his DCS folder, therefore the app complained that it couldn't find it. Users of the App that have used it previously will have that particular folder on their system already, and would not encounter this message.

For this section we still need to select and declare the DCS mod folder but we should get rid of this as a check as it already looks for the DCS/Liveries folder.

Future testing should test this App on "Virgin" systems to ensure it will work for new users.
Thoughts @fiddyschmitt ?

**Comment by fiddyschmitt** [comment]
I've removed the OGN_Mods folder and it works fine. Is it possible it's complaining about the Liveries folder not existing?

**Comment by fiddyschmitt** [comment]
Also, can you please post the full path to the DCS folder? Mine is:
C:\Users\smith\Saved Games\DCS.openbeta

**Comment by MacGynan** [comment]
My one is:
C:\Users\macgynan\Saved Games\DCS\

But i reported the bug for Hunter. I'll ask hunter as to what his is. But i believe it is the same as yours. I just remember looking at the options menu and it not a folder selected for the liveries folder. I believe the issue is that he did not have a liveries folder created so i did not pick it up. The app might need to try to detect it, and if not found create it.

For some weird reason. DCS does not automatically create a liveries folder by default.

**Comment by Azza276** [comment]
Hi @MacGynan , yeah, I've spoken to Hunter myself. I think we just need to check for the DCS or DCS.openbeta, DCS.openalpha folders, not necessarily for the mods folder or  liveries folder as they will be created during the Sync Process. 

When I spoke to Hunter, he said it was for the Mods folder but may well have been for liveries as well, not sure what DCS creates when first installed and ran, hence why this was not found earlier.

**Comment by fiddyschmitt** [comment]
Thanks guys, I've just committed a change so that the Liveries folder is treated the same way as the OGN_Mods folder. ie. When the 'Verify' button is clicked, it creates the Liveries folder if it doesn't already exist.

**Comment by MacGynan** [comment]
@Azza276 I do believe hunter was wrong. It was the top option which was the Liveries folder. But that is great @fiddyschmitt. That should of solved the issue. When the update comes out i will test it.

**Comment by Azza276** [comment]
Yeah fair enough @MacGynan . I didn't know if the game created the liveries. That being said, the Mods folder could probably also be checked and created later too.

**Comment by Azza276** [comment]
Hotfix1 for 0.3 Alpha Added. This change will be released to that. Just need to change Titlebar text. Otherwise this bug is now closed. Thanks @MacGynan & @fiddyschmitt
